# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0babe73fd7e02697b4fc2606d4d9d37680ff2f716a97606f5e07aafbccd33240ab672e47abaaa7b746375de1e4f03b4ca5bbe143c6bb852599adfa84c7a66f3

test:
  secret_key_base: 4a65aff5cc9b43dfdd797b4c937fe67358250cc58ca21927a3fb8fb0edc861c3705e0057e23cc22796289a8550e8f6d55610ce5dd6a71c9495d59a9d2361a19c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
